debug: true
spring:
  application:
    name: GraphQL Example
graphql:
  servlet:
#    mapping: /graphql
    enabled: true
    actuator-metrics: true

#    corsEnabled: true
#    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
#    exception-handlers-enabled: true
#  tools:
#    schema-location-pattern: "**/*.graphqls"
#    # Enable or disable the introspection query. Disabling it puts your server in contravention of the GraphQL
#    # specification and expectations of most clients, so use this option with caution
#    introspection-enabled: true
graphiql:
#  mapping: /graphiql
#  endpoint:
#    graphql: /graphql
#    subscriptions: /subscriptions
#  subscriptions:
#    timeout: 30
#    reconnect: false
#  static:
#    basePath: /
  enabled: true
#  pageTitle: GraphiQL
  cdn:
    enabled: false
    version: 0.13.0
#  props:
#    resources:
#      query: example.graphql.web.controller.graphql.dto
#      defaultQuery: example.graphql.web.controller.graphql.Query
#      variables: variables.graphql
#    variables:
#      editorTheme: "solarized light"
